version: 0.2

phases:
  install:
    commands:
      - apt-get update -y
  build:
    commands:
      - printenv
      - dotnet restore
      - dotnet build
      - cd CiTest
      - dotnet publish -c Release -o publish
      - docker build -t $IMAGE_REPO_NAME:latest .
      - docker tag $IMAGE_REPO_NAME:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest