version: 0.2

phases:
  install:
    commands:
      - apt-get update -y
  build:
    commands:
      - chmod +x set-codebuild-env.sh
      - . ./set-codebuild-env.sh
      - dotnet restore
      - dotnet build
      - cd CiTest
      - dotnet publish -c Release -o publish
      - docker build -t $IMAGE_REPO_NAME:$CODEBUILD_GIT_BRANCH .
      - docker tag $IMAGE_REPO_NAME:$CODEBUILD_GIT_BRANCH $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$CODEBUILD_GIT_BRANCH
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$CODEBUILD_GIT_BRANCH